# Generated by Django 3.1.12 on 2025-09-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiml_1',
            name='course',
        ),
        migrations.RemoveField(
            model_name='aiml_1',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='aiml_1',
            name='year',
        ),
        migrations.AddField(
            model_name='aiml_1',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aiml_1',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiml_1',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.faculty', to_field='subject'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subject',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='aiml_1',
            table=None,
        ),
        migrations.AlterModelTable(
            name='faculty',
            table=None,
        ),
    ]
